---
- hosts: devserver
  become: yes
  ignore_errors: yes
    tasks:
      - name: install package
        package:
         name: "{{ item }}"
         state: present
      with_items:
        - wget
        - unzip
        - httpd
      - name: download and extract doc 
         wget_url:
